[platformio]
default_envs = bare_meshcore
src_dir = main
test_dir = test

[espidf_base]
framework = espidf
monitor_speed = 115200

[env:bare_meshcore]
extends = espidf_base
platform = platformio/espressif32@6.11.0
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
upload_speed = 115200
test_ignore = *
build_flags =
    -D ESP32_PLATFORM
    -D P_LORA_NSS=7
    -D P_LORA_SCLK=5
    -D P_LORA_MISO=3
    -D P_LORA_MOSI=6
    -D P_LORA_DIO_1=16
    -D P_LORA_BUSY=15
    -D P_LORA_RESET=8
    -D SX126X_RXEN=4
    -D SX126X_TXEN=9

[env:native]
platform = native
test_framework = unity
targets = test
build_src_filter = -<*>
build_flags =
    -I main

